<!-- Contact Form Section -->
<section id="contact-us" class="col center horizontal">

    <h2 id="content-title" class="center horizontal" style="margin-bottom: 1rem;">Contact HR</h2>
    <p class="center horizontal" style="margin-top: 0;">If you don't have an email address, please enter a phone number to best contact you by.</p>
    <p class="center horizontal">Please select one of the options below to get started!</p>
    <div class="content-selector center horizontal wrap">
        <div class="content-selector-button" id="human-resources-button">Contact HR</div>
        <div class="content-selector-button" id="esp-button">Contact Employee Suggestion Program</div>
        <div class="content-selector-button" id="tipline-button">Contact "Tip" Hotline</div>
    </div>
    <form class="col" action="javascript:void(0);" style="display: none">

        <div class="success col">
            <h1>Submitted!</h1>
            <p>Thank you for reaching out to us. We will get back to you as soon as possible.</p>
        </div>
        <div class="error col">
            <h1>Error!</h1>
            <p>Sorry, we were unable to submit your message! Please try again later.</p>
        </div>

        <div class="loading hidden"></div>

        <div class="row fill wrap" notip>
            <div class="col fill floating-input">
                <input type="text" id="fname" name="fname" placeholder="">
                <label for="fname">First Name</label>
            </div>
            <div class="col fill floating-input">
                <input type="text" id="lname" name="lname" placeholder="">
                <label for="lname">Last Name</label>
            </div>
        </div>
        <div class="row fill wrap" notip>
            <div class="col floating-input fill">
                <input type="email" id="email" name="email" placeholder="">
                <label for="email">Email</label>
            </div>
            <div class="col floating-input fill">
                <input type="tel" id="phone" name="phone" placeholder="">
                <label for="phone">Phone</label>
            </div>
        </div>
        <div class="col floating-input">
            <input type="text" name="subject" id="subject" placeholder="">
            <label for="subject">Subject</label>
        </div>
        <div class="col floating-input">
            <textarea name="message" id="message" cols="30" rows="10" required></textarea>
            <label for="message">Message</label>
        </div>

        <button id="submit-button" title="Submit contact form!"><i class="fa-solid fa-paper-plane"></i></button>
        <button id="full-submit-button" style="display: none">Submit <i class="fa-solid fa-paper-plane"></i></button>
    </form>
</section>