<!-- HR Contact Section -->
<section id="hr-contact-info" class="col">
    <h2>HR Contact Information</h2>
    <div class="row wrap">
        <div id="cathy-contact" class="panel col fill center vertical">
            <h4>Cathy Callahan</h4>
            <ul>
                <li>Email:<b> ccallahan@mardens.com</b></li>
                <li>
                    Phone: <b>
                        (207) 660-9218</b>
                </li>
                <li>
                    Cellphone: <b> (207) 649-3067</b>
                </li>
            </ul>
            <br>
            <hr style="width: 50%;">
            <br>
            <div class="row">
                <a href="mailto:ccallahan@mardens.com" target="_blank" class="button"><i class="fa-solid fa-envelope"></i></a>
                <a href="tel:207-660-9218" target="_blank" class="button"><i class="fa-solid fa-phone"></i></a>
                <a href="tel:207-649-3067" target="_blank" class="button"><i class="fa-solid fa-mobile"></i></a>
            </div>
        </div>
        <div id="tiffany-contact" class="panel col fill center vertical">
            <h4>Tiffany Bernatchez</h4>
            <ul>
                <li>
                    Email: <b> tiffany.bernatchez@mardens.com</b>
                </li>
                <li>
                    Phone: <b> (207) 830-4045</b>
                </li>
            </ul>
            <br>
            <hr style="width: 50%;">
            <br>
            <div class="row">
                <a href="mailto:tiffany.bernatchez@mardens.com" target="_blank" class="button"><i class="fa-solid fa-envelope"></i></a>
                <a href="tel:207-830-4045" target="_blank" class="button"><i class="fa-solid fa-phone"></i></a>
            </div>
        </div>
    </div>
</section>
