<!-- Phone Banners Section -->
<section class="banner row fill">
    <div id="tip-line-banner" class="col fill">
        <h2>Employee "Tip" Hotline</h2>
        <p>See something suspicious? Report it anonymously</p>
        <a href="tel:240-800-6273">240-800-6273</a>
    </div>
    <div id="eap-banner" class="col fill">
        <h2>Employee Assistance Program</h2>
        <p>Counseling/Daily Life Assistance/Legal & Financial Services</p>
        <a href="tel:1-888-628-4824">1-888-628-4824</a>
        <button onclick="openEAP()">View the EAP PDF</button>
    </div>
</section>

<script>
    function openEAP()
    {
        window.open('/assets/pdf/Lincoln EAP - PDF 2025.pdf', "_blank")
    }
</script>